# THEME REDEFINE CONFIGURATION FILE V2
# BY EVANNOTFOUND
# GITHUB: https://github.com/EvanNotFound/hexo-theme-redefine
# DOCUMENTATION: https://redefine-docs.ohevan.com

# BASIC INFORMATION
info:
  title: B1yat's Blog
  subtitle: ฅ՞•ﻌ•՞ฅ
  author: b1yat
  url: https://Iamb1yat.github.io

# IMAGE CONFIGURATION
defaults:
  favicon: /images/redefine-favicon.png
  logo: 
  avatar: /images/redefine-avatar.jpg

# COLORS
colors:
  primary: "#6B8DFF"
  secondary: "#8A9FFF"
  default_mode: light

# SITE CUSTOMIZATION
global:
  fonts:
    chinese: 
      enable: false
    english: 
      enable: false
    title:
      enable: true
      family: "'Noto Sans SC', 'Helvetica Neue', Helvetica, Arial, sans-serif"
  content_max_width: 1000px
  sidebar_width: 210px
  hover:
    shadow: true
    scale: true
  scroll_progress:
    bar: true
    percentage: true
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true
    site_uv: true
    post_pv: true
  single_page: true
  preloader:
    enable: true
    custom_message: "B1yat's Blog"
  open_graph:
    enable: true
    image: /images/redefine-og.webp
    description: "Welcome to my sekai"

# FONTAWESOME
fontawesome:
  thin: false
  light: false
  duotone: false
  sharp_solid: false

# HOME BANNER
home_banner:
  enable: true
  style: fixed
  image: 
    light: /images/wallhaven-wqery6.png
    dark: /images/wallhaven-wqery6.png
  title: Welcome to my sekai
  subtitle:
    text: ["風をまとい、光を追う✨", "無垢なる浪漫..(ˊᗜˋ)/♡"]
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
  text_color: 
    light: "#2c3e50"
    dark: "#2c3e50"
  text_style:
    title_size: 3.5rem
    subtitle_size: 1.5rem
    line_height: 2
    text_shadow: false
    font_weight: 600
  custom_font:
    enable: false
  social_links:
    enable: true
    style: default
    position: right
    layout: horizontal
    mobile: true
    links:
      github:  https://github.com/Iamb1yat
      email: mailto:b1yat@icloud.com
      bilibili: https://space.bilibili.com/364646464
    qrs:
      weixin: /images/about/wechat-qr.png
      qq: /images/about/qq-qr.png

# NAVIGATION BAR
navbar:
  auto_hide: false
  color:
    left: "rgba(255, 255, 255, 0.9)"
    right: "rgba(255, 255, 255, 0.9)"
    transparency: 10
  blur: false
  style:
    text_color: "#2c3e50"
    text_weight: 600
  width:
    home: 1200px
    pages: 1000px
  links:
    Home: 
      path: /
      icon: fa-regular fa-house
    文章: 
      path: /archives
      icon: fa-regular fa-archive
    标签: 
      path: /tags
      icon: fa-regular fa-tags
    分类: 
      path: /categories
      icon: fa-regular fa-folder
    Links:
      icon: fa-regular fa-star
      submenus:
        资源分享: /resources
        工具推荐: /tools
    关于: 
      path: /about
      icon: fa-regular fa-user
  search:
    enable: true
    preload: true

# HOME PAGE ARTICLE SETTINGS
home:
  sidebar:
    enable: true
    position: left
    first_item: menu

# ARTICLE SETTINGS
articles:
  style:
    font_size: 16px
    line_height: 1.8
    image_border_radius: 14px
    image_alignment: center
    image_caption: false
    link_icon: false
  word_count:
    enable: true
    count: true
    min2read: true
  author_label:
    enable: true
    auto: false
    list: ["生まれてよかった..."]
  code_block:
    copy: true
    style: mac
    font:
      enable: false
  toc:
    enable: true
    max_depth: 3
    number: false
    expand: true
    init_open: true
  copyright:
    enable: true
    author: true
    link: true
    license: CC BY-NC-SA 4.0
    license_link: https://creativecommons.org/licenses/by-nc-sa/4.0/


comment:
  # Whether to enable comment
  enable: true
  # Comment system
  system: gitalk
  # System configuration
  config:
    gitalk:
      clientID: Ov23liq2fiQzooWJAry8
      clientSecret: 2d86e55d52819ff01c5cb7033ed5d70f60320a4d
      repo: gitalk
      owner: Iamb1yat
      proxy: https://strong-caramel-969805.netlify.app/github_access_token
# COMMENT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# FOOTER SETTINGS
footer:
  runtime: true
  start: 2024/02/10 00:00:00
  customize: false
  icp:
    enable: false
    number: 
    url: 

# PLUGINS
plugins:
  aplayer:
    enable: false
  mermaid:
    enable: true
    version: "9.3.0"
  katex:
    enable: false
  mathjax:
    enable: true
    version: "latest"
  typed:
    enable: true
    version: "2.0.12"
  pangu:
    enable: true
    version: "4.0.7"

# CDN
cdn:
  enable: true
  provider: npm

# NEW LINKS CONFIGURATION
links:
  - links_category: 技术大佬
    items:
      - title: 示例博主
        link: https://example.com
        avatar: /images/avatar-default.png
        description: 这里是博主的简介

  - links_category: 学习伙伴
    items:
      # 这里可以添加更多友链 